### ISSUE TITLE
FaiAppelloController controllo docente

### ISSUE THREAD

**Issue by rotz87** [rotz87/ing_soft#2]
Vedere se si deve controllare l'esistenza dell'appello in FaiAppelloController.getAssenze  (come sta fatto in FaiAppelloController.getBoolAssenze).

**Comment by LORENZDIM** [comment]
Secondo me non serve, il controllo sulle assenze prese viene fatto da getAssenzeNoExeption che viene utilizzata da getAssenze, inoltre se si manda un idAppello che non esiste già viene lanciata un'eccezione, (tramite l'interfaccia non è comunque possibile arrivare a chiedere le assenze di un appello null)
