### ISSUE TITLE
Gestione eccezioni (lato client)

### ISSUE THREAD

**Issue by rotz87** [rotz87/ing_soft#3]
- Quando un docente non autorizzato su una certa classe, crea un nuovo appello non compare il popup di errore;
- Quando un docente non autorizzato su una certa classe, inserisce le assenze su un appello già creato compare il popup, ma non usa il messaggio dell'eccezione del server (exMsg).

**Comment by MattMic87** [comment]
bug corretti con l'ultimo commit
